### ISSUE TITLE
Rust 1.0?

### ISSUE THREAD

**Issue by pataroose** [PistonDevelopers/asset_store#19]
Any chance this will be updated? I tried to get things running, but I don't have enough knowledge about Rust to make the transition. `rust-package` also needs to be updated, and I tried and failed there too. =)

**Comment by bvssvni** [comment]
I also want this updated! :+1:

**Comment by pataroose** [comment]
I'm in a position where I'm not doing much every day besides learning and working with rust, so if it's not urgent (judging by the state of this project, probably not :sob:) I can take care of it at some point in the future.

**Comment by bvssvni** [comment]
@pataroose How is it going? Have you faced some big obstacles?

**Comment by pataroose** [comment]
I did, and things are starting to make sense :smiley:. I updated rust-package to 1.0 and will probably end up switching out 'asset_store's backend dependency on hyper because it required SSL developer libraries for Windows users which seemed like a big hassle. Will try to get that out soon.

**Comment by bvssvni** [comment]
Nice!

**Comment by mitchmindtree** [comment]
Just thought I'd drop by and mention that [this](https://github.com/PistonDevelopers/find_folder) might be handy for having the AssetStore automatically find the `assets` folder before it goes to work.

**Comment by pataroose** [comment]
I have `iostore` and the general lib compiling at pataroose@c6cff2f77b but it seems as though I've been fighting the same problem #15 that @bvssvni had. Removing [this comment block](https://github.com/pataroose/asset_store/blob/c6cff2f77bd57e532a7a80750e3175273d843822/src/multi_store.rs#L87-115) in multi_store leaves the following compilation error:

```
src\multi_store.rs:99:48: 99:65 error: cannot convert to a trait object because trait `AssetStore` is not object-safe [E0038]
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `load_all` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `all_loaded` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `unload_all` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `map_resource` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `map_resource_block` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `with_bytes` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
src\multi_store.rs:99:48: 99:65 note: method `with_bytes_block` has generic type parameters
src\multi_store.rs:99         self.stores.insert(prefix.to_string(), Box::new(wrapped));
                                                                     ^~~~~~~~~~~~~~~~~
```
Besides putting off fighting with it and instead working on the static store since `rust-package` can compile now, I'm not sure how to proceed.

@mitchmindtree Good idea! Your code looks great, I will definitely look into it more.

**Comment by bvssvni** [comment]
@pataroose One idea is to remove the generic parameter on the trait and use a common `Error` struct for all the asset stores.

**Comment by bvssvni** [comment]
@pataroose I forgot you had it working and merged some PRs. We could merge the changes as we fix them and work against master, since it is broken anyway.

**Comment by bvssvni** [comment]
@pataroose I rebased your changes.

Closed https://github.com/PistonDevelopers/asset_store/pull/26
